import type { ManualDocument } from "@/lib/types";

/** 관련 문서 파일명 목록 Seed — 매뉴얼 본문·부록에서 인용된 문서 기준 */
export const DOCUMENTS: ManualDocument[] = [
  {
    id: "doc-busan-flood-2026",
    fileName: "부산광역시_풍수해(태풍·호우·대설)_재난_현장조치_행동매뉴얼_2026.7.pdf",
    disasterTypes: ["flood", "typhoon", "heavy_snow"],
    organization: "부산광역시",
    category: "행동매뉴얼",
    year: 2026,
    pages: 445,
    description: "자연재난-1. 재난대응 단계별 행동요령(징후감지·초기대응·비상대응·수습복구) 113개 조치카드",
  },
  {
    id: "doc-flood-practice",
    fileName: "풍수해_재난_위기관리_실무매뉴얼_행정안전부.pdf",
    disasterTypes: ["flood", "typhoon", "heavy_snow"],
    organization: "행정안전부",
    category: "실무매뉴얼",
    year: 2025,
    description: "풍수해 재난 위기관리 표준·실무 절차",
  },
  {
    id: "doc-river-safety-2023",
    fileName: "하천_안전사고_예방대책_매뉴얼_2023.10.pdf",
    disasterTypes: ["flood", "typhoon"],
    organization: "부산광역시",
    category: "지침",
    year: 2023,
    description: "호우예비특보 발효 시 하천 진·출입 통제 기준",
  },
  {
    id: "doc-evacuation-order",
    fileName: "재난현장_대피명령_세부지침(부록5).pdf",
    disasterTypes: ["flood", "typhoon", "heavy_snow", "wildfire"],
    organization: "부산광역시",
    category: "지침",
    year: 2026,
    description: "사전대피·대피명령·안전취약계층 대피 고려사항",
  },
  {
    id: "doc-relief-plan",
    fileName: "부산광역시_재해구호계획_임시주거시설_지정현황.pdf",
    disasterTypes: ["flood", "typhoon", "heavy_snow", "wildfire"],
    organization: "부산광역시 복지정책과",
    category: "복구",
    year: 2026,
    description: "이재민 임시주거시설·구호물자 지원 절차",
  },
  {
    id: "doc-recovery-report-form",
    fileName: "기상특보_대처상황_결과보고_서식(부록1).pdf",
    disasterTypes: ["flood", "typhoon", "heavy_snow"],
    organization: "부산광역시",
    category: "복구",
    year: 2026,
    description: "상황보고·피해복구 일일상황보고·결과보고 서식",
  },
  {
    id: "doc-wildfire-2024",
    fileName: "산불재난_위기대응_실무매뉴얼_환경부_2024.10.pdf",
    disasterTypes: ["wildfire"],
    organization: "환경부",
    category: "실무매뉴얼",
    year: 2024,
    pages: 182,
    description: "사회재난-01. 위기경보 수준별 조치사항·재난상황별 조치내용",
  },
  {
    id: "doc-wildfire-standard",
    fileName: "산불재난_위기관리_표준매뉴얼_산림청.pdf",
    disasterTypes: ["wildfire"],
    organization: "산림청",
    category: "실무매뉴얼",
    year: 2024,
    description: "산불 위기경보 발령체계·진화자원 동원",
  },
  {
    id: "doc-safe-korea-guide",
    fileName: "2026_안전한국훈련_실시_가이드라인_행정안전부.pdf",
    disasterTypes: ["flood", "typhoon", "heavy_snow", "wildfire"],
    organization: "행정안전부",
    category: "훈련",
    year: 2026,
    description: "훈련계획·시나리오·상황메시지 작성 및 평가",
  },
  {
    id: "doc-citizen-guide",
    fileName: "시민행동요령_풍수해(부록6).pdf",
    disasterTypes: ["flood", "typhoon", "heavy_snow"],
    organization: "부산광역시",
    category: "지침",
    year: 2026,
  },
];
