import type { RecommendedAction } from "@/lib/types";

const D = "doc-wildfire-2024";

/** 산불 재난 위기대응 실무매뉴얼(환경부, 2024) Ⅳ·Ⅴ장 기반 교차검증 Seed */
export const WILDFIRE_ACTIONS: RecommendedAction[] = [
  {
    id: "wf-가-1",
    code: "가-1",
    title: "산불발생 접수·보고·전파",
    summary: "위기경보 발령·산불발생 상황 전파 및 보고",
    stage: "징후감지",
    leadDept: "자연공원과(상황반)",
    supportDept: "종합상황실",
    coopAgencies: "산림청, 행정안전부, 국립공원공단",
    details: [
      "산불발생 지역·명칭, 발생시간, 규모·진행상황, 진화자원 동원상황 전파·보고",
      "재난담당부서·유관기관 전파",
      "주요시설(상·하수도, 매립장, 국립공원 등) 초기 피해상황 파악 및 보고",
    ],
    targets: ["장관·차관", "실·국장", "유관기관"],
    resources: [],
    sourceDocId: D,
    page: 62,
  },
  {
    id: "wf-가-2",
    code: "가-2",
    title: "상황판단회의 개최",
    summary: "위기수준 평가 및 비상단계 발령",
    stage: "초기대응",
    leadDept: "자연공원과",
    supportDept: "자연보전국",
    coopAgencies: "산림청",
    details: [
      "구성: 자연보전국장, 자연공원과장 등 (긴급 시 직제순 최고 선임자 주재)",
      "수집 상황정보 종합 → 위기수준 평가 → 위기경보 발령·변경·해제",
      "야간·공휴일은 유·무선, 문자·SNS로 간략 협의 후 결과 전파",
    ],
    targets: ["실·국장", "유관기관"],
    resources: [],
    sourceDocId: D,
    page: 41,
  },
  {
    id: "wf-나-1",
    code: "나-1",
    title: "피해현황 파악 및 보고",
    summary: "국립공원 등 인명·시설 피해현황 파악",
    stage: "초기대응",
    leadDept: "자연공원과(상황반)",
    supportDept: "실무반",
    coopAgencies: "국립공원공단, 유역(지방)환경청",
    details: [
      "산불로 인한 국립공원 등 인명·시설 피해현황 파악 및 보고",
      "소관 시설물 피해현황 파악 및 재난상황실 보고",
      "대처상황 보고서 작성 및 전파",
    ],
    targets: ["장관·차관", "행정안전부"],
    resources: [],
    sourceDocId: D,
    page: 63,
  },
  {
    id: "wf-나-2",
    code: "나-2",
    title: "초기대응 지시(긴급 구조·탐방객 통제)",
    summary: "긴급 구조/복구, 탐방객·우려지역 통제·예찰",
    stage: "초기대응",
    leadDept: "자연공원과",
    supportDept: "국립공원공단",
    coopAgencies: "소방청, 경찰청",
    details: [
      "인명·시설피해에 대한 소관사항별 긴급 구조/복구",
      "탐방객 및 재해 발생·우려지역 통제/예찰",
      "국립공원 탐방객 단계별 통제조치 시행",
      "등산객 인화물질 소지행위 사전차단",
    ],
    targets: ["국립공원 탐방객", "유관기관"],
    resources: ["진화장비", "차량"],
    sourceDocId: D,
    page: 63,
  },
  {
    id: "wf-다-0",
    code: "다-0",
    title: "국립공원·인근지역 산불진화 지원",
    summary: "헬기 등 진화자원 투입 및 위치정보 제공",
    stage: "비상대응",
    leadDept: "국립공원공단",
    supportDept: "자연공원과",
    coopAgencies: "산림청, 소방청, 국방부",
    details: ["국립공원 위치정보 제공 및 헬기 등 진화자원 투입 진화", "산불취약지역 순찰·점검 강화", "고립 인명 구조"],
    targets: ["산림청", "소방청"],
    resources: ["산불진화헬기", "진화차량", "진화인력"],
    sourceDocId: D,
    page: 68,
  },
  {
    id: "wf-다-1",
    code: "다-1",
    title: "소관사항별 대응조치",
    summary: "인명·시설피해에 대한 소관사항별 피해 대응/복구",
    stage: "비상대응",
    leadDept: "실무반(각 소관부서)",
    supportDept: "종합상황실",
    coopAgencies: "유역(지방)환경청, 한국환경공단, 수자원공사",
    details: [
      "소관 환경시설 및 댐 등 지도·점검 강화",
      "피해시설(지역) 처리대책 지원",
      "피해지역 폐기물 처리대책 지원",
      "취·정수장 점검 및 긴급급수 지원",
    ],
    targets: ["소관부서", "산하기관"],
    resources: ["긴급급수차", "장비"],
    sourceDocId: D,
    page: 63,
  },
  {
    id: "wf-다-2",
    code: "다-2",
    title: "인력지원 및 홍보",
    summary: "인력동원 관리, 대국민 브리핑·보도자료 배포",
    stage: "비상대응",
    leadDept: "운영지원과·대변인실(지원반)",
    supportDept: "자연공원과",
    coopAgencies: "언론매체",
    details: [
      "대규모 산불 진화 위한 긴급 인력동원 관리",
      "언론매체(중앙/지역)·SNS·홈페이지 재난방송 및 보도자료 작성·배포",
      "언론브리핑 및 대국민 담화문 발표",
      "언론 모니터링 및 오보대응",
    ],
    targets: ["언론", "국민"],
    resources: ["인력"],
    sourceDocId: D,
    page: 63,
  },
  {
    id: "wf-비-3",
    code: "비-3",
    title: "종합상황실 24시간 비상근무",
    summary: "비상 3단계 근무편성 및 운영",
    stage: "비상대응",
    leadDept: "자연공원과",
    supportDept: "상황반·실무반",
    coopAgencies: "행정안전부",
    details: ["구성: 상황반 1+α명, 실무반 각 반별 1명", "24시간 종합상황실 비상근무 체계 유지", "장관·차관·자연보전국장 주기적 보고"],
    targets: ["장관·차관"],
    resources: ["인력"],
    sourceDocId: D,
    page: 46,
  },
  {
    id: "wf-라-1",
    code: "라-1",
    title: "위기경보 해제 접수·보고·전파",
    summary: "해제결정 보고 및 유관기관 전파",
    stage: "수습·복구",
    leadDept: "자연공원과(상황반)",
    supportDept: "종합상황실",
    coopAgencies: "산림청, 유관기관",
    details: ["위기경보 해제 결정 시 해제결정 보고", "유관기관 전파", "비상근무 종료"],
    targets: ["실·국장", "유관기관"],
    resources: [],
    sourceDocId: D,
    page: 63,
  },
  {
    id: "wf-라-2",
    code: "라-2",
    title: "피해복구 및 이재민 지원",
    summary: "피해상황 조사·복구지원·구호물품 지원",
    stage: "수습·복구",
    leadDept: "소관반별",
    supportDept: "운영지원과",
    coopAgencies: "행정안전부, 지자체",
    details: [
      "피해상황 조사 및 피해지역 복구지원",
      "이재민 구호물품 지원",
      "재난·사고 원인조사 및 재발방지대책 수립",
      "피해 복구 상황보고서 작성·보고·전파",
    ],
    targets: ["이재민", "행정안전부"],
    resources: ["구호물품", "복구장비"],
    sourceDocId: D,
    page: 63,
  },
];
